### ISSUE TITLE
New FavIcon

### ISSUE THREAD

**Issue by JakeM93** [directtoanne/fin-man#25]
FavIcon is currently a caravan.
Maybe we should have it financial related

**Comment by JakeM93** [comment]
Used logo as the Favicon as its currently a caravan
![image](https://user-images.githubusercontent.com/76944122/130322004-d06c3198-662d-46ee-83f9-c202e176a23b.png)

**Comment by directtoanne** [comment]
> Used logo as the Favicon as its currently a caravan
> ![image](https://user-images.githubusercontent.com/76944122/130322004-d06c3198-662d-46ee-83f9-c202e176a23b.png)

didnt realise u actly did this... do u mind checking the icon i did on slack and letting me know if its okay or not... if not we can use urs no biggie bahahah 😅
